name: Docker Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  docker-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker Images
        run: |
          docker buildx build --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 -t wiredlush/luna-dns:$RELEASE_VERSION --push .
          docker buildx build --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 -t wiredlush/luna-dns:latest --push .
